name: Publish to Github Pages
on:
  push:
    branches:
      - main

jobs:
  # Build the registry
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install registry tooling
        run: npm i
      - name: Generate registry index
        run:
          npm run build
          rm -rf node_modules
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  # Deployment the registry to Github Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
